## Домашнее задание №0 - Основные математические понятия

In [33]:
# Импортируем библиотеки
import numpy as np

# Для манипуляций с функциями и их производными
import sympy as sym

### Задание 1.

Представить фильмы в виде бинарных векторов (numpy array) используя следующие признаки:

[Комедия, Боевик, Исторический, Бред Питт, Бенедикт Камбербэтч, Квентин Тарантино]

1. Игра в имитацию [https://www.kinopoisk.ru/film/635772/]
2. Ярость [https://www.kinopoisk.ru/film/740644/]
3. 12 лет рабства [https://www.kinopoisk.ru/film/606646/]
4. Однажды в Голливуде [https://www.kinopoisk.ru/film/1047883/]

In [5]:
# Зададим структуру векторов с сокращенной информацией о фильмах
film_fields = ['comedy', 'action', 'history', 'Brad_Pitt', 'Benedict_Cumberbatch', 'Quentin_Tarantino']
# Значения вектора принимают значения 0 (если данный признак не актуален для текущего фильма и 1 в противном случае)
# Игра в имитацию (хотя в явном виде жанр history не указан, фильм снят на основе реальной биографии главного героя;
# Тем не менее буду формалистом: этот фильм не относится ни к одному из заданных жанров)
film_1=np.array([0,0,0,0,1,0])

# Ярость
film_2=np.array([0,1,0,1,0,0])

# 12 лет рабства
film_3=np.array([0,0,1,1,1,0])

# Однажды в Голливуде (поскольку в условиях задачи не задано, какую именно роль указанного человека надо фиксировать,
# не могу не указать Тарантино для фильма, который он снял, хотя вроде бы в качестве актера он в этом фильме не снялся)
film_4=np.array([1,0,0,1,0,1])

# Для удобства выполнения ряда последующих заданий создадим словарь
films = {
    'Игра в имитацию': film_1,
    'Ярость': film_2,
    '12 лет рабства': film_3,
    'Однажды в Голливуде': film_4
}

### Задание 2.

Вычислить Евклидову норму каждого из векторов, полученных в Задании 1.

In [10]:
# Используем для вычисления Евклидовой нормы функцию norm метода linalg библиотеки np
for f_title, f_vect in films.items():
    print(f'Евклидова норма для фильма «{f_title}» равна {round(np.linalg.norm(f_vect), 2)}')


Евклидова норма для фильма «Игра в имитацию» равна 1.0
Евклидова норма для фильма «Ярость» равна 1.41
Евклидова норма для фильма «12 лет рабства» равна 1.73
Евклидова норма для фильма «Однажды в Голливуде» равна 1.73


### Задание 3.

Найти угол между векторами-фильмами "Ярость" и "12 лет рабства". Результатом будет являться косинусная мера, которую можно использовать для определения похожести векторов.  

In [16]:
# Вначале посчитаем скалярное расстояние между векторами нужных нам фильмов:
s_dist = np.dot(films['Ярость'], films['12 лет рабства'])
#s_dist
# Теперь вычислим косинус угла между этими векторами
films_cos = s_dist/(np.linalg.norm(films['Ярость'])*np.linalg.norm(films['12 лет рабства']))
films_cos
# Получив значение косинуса, вычислим угол между векторами в радианах и в градусах
angle_rad = np.arccos(films_cos)
#angle_rad
# Варианты перевода радианов в градусы: прямое вычисление или использование спец. функции
#angle_degree = np.rad2deg(angle_rad)
angle_degree = angle_rad*180/np.pi
angle_degree

65.90515744788931

### Задание 4.

Объединить векторы, полученные в Задании 1 в матрицу, где каждый вектор является строкой матрицы. Полученную матрицу умножить на вектор [1,2,3,4]

In [56]:
# Вначале создаем список списков, а потом делаем из него матрицу
films_list = []
for film in films:
    # Преобразуем вектор фильма в массив и добавляем его как новый элемент к списку films_list
    films_list.append(films[film].tolist())
# Создаем матрицу
films_matrix = np.array(films_list)
# Создаем вектор
test_vector = np.array([[1,2,3,4]])
print(f'films_matrix =\n{films_matrix},\ntest_vector =\n{test_vector}')

# При умножении матриц необходимо выполнение условия, 
# что количество столбцов в умножаемой матрице равно количеству строк матрицы, на которую идет умножение
# В нашем случае по условию задачи требуется умножить матрицу 4x6 на вектор 1x4, и такое умножение невозможно.
# Чтобы умножение получилось, либо надо поменять множители местами (вектор умножить на матрицу),
# либо транспонировать матрицу и вектор и после этого умножить транспонированную матрицу на траспонированный вектор
#multiplied_films = films_matrix*test_vector     # выдает ошибку

# Первый вариант - умножение вектора на матрицу
print(np.dot(test_vector,films_matrix))

# Второй вариант - умножение транспонированных матрицы и вектора и транспонирование результата:
print(np.dot(films_matrix.transpose(),test_vector.transpose()).transpose())

# Видно, что оба способа дали один и тот же результат.

films_matrix =
[[0 0 0 0 1 0]
 [0 1 0 1 0 0]
 [0 0 1 1 1 0]
 [1 0 0 1 0 1]],
test_vector =
[[1 2 3 4]]
[[4 2 3 9 4 4]]
[[4 2 3 9 4 4]]


### Задание 5.

Вычислить на бумаге и с помощью Python значение первой и второй производной для функции $3x(x^2+x)^3$ в точке $x=1$

In [57]:
# Это задание частично было разобрано во время лекции, так что ради интереса часть кода поменяю.
x = sym.Symbol('x')

In [71]:
# Задаем исходную формулу
src = 3*x*(x**2+x)**(3)
src

3*x*(x**2 + x)**3

In [72]:
# Для упрощения процедуры дифференцирования и повышения наглядности развернем эту формулу с помощью функции expand
src_2 = sym.expand(src)
src_2

3*x**7 + 9*x**6 + 9*x**5 + 3*x**4

In [73]:
# Вычисляем первую производную раскрытого выражения
res_1=sym.diff(src_2,x)
res_1

21*x**6 + 54*x**5 + 45*x**4 + 12*x**3

In [74]:
# Сразу же вычисляем и вторую производную
res_2 = sym.diff(res_1)
res_2

126*x**5 + 270*x**4 + 180*x**3 + 36*x**2

In [76]:
# Выводим результаты
print(f'В точке х=1 значение первой производной = {res_1.subs(x,1)}, значение второй производной = {res_2.subs(x,1)}')

В точке х=1 значение первой производной = 132, значение второй производной = 612


In [81]:
# Интересно было бы как-то упростить функции для производных, но получающиеся результаты упрощения кажутся не идеальными:
sym.simplify(res_1)

x**3*(21*x**3 + 54*x**2 + 45*x + 12)

In [82]:
sym.simplify(res_2)

x**2*(126*x**3 + 270*x**2 + 180*x + 36)